language: cpp
sudo: required
dist: trusty
compiler:
- clang
- gcc
os:
- linux
- windows
before_install:
- echo $LANG
- echo $LC_ALL
branches:
- master
notifications:
  email:false
env:
 global:
 - LANG="en_US.UTF-8"

